### ISSUE TITLE
Is it possible to "tell" the cobol extension to parse copybooks not in the source?

### ISSUE THREAD

**Issue by GitMensch** [spgennard/vscode_custom_cobol#2]
Different preparsers auto-include copybooks, depending on macros or similar stuff that is used. Example:

```cobol
testme section.
   #OPEN(myFile)
   MOVE myfile-var1 TO B
   DISPLAY myfile-var2
   .
```

And this `#OPEN` now auto-includes `myFileFD.CPY`´ where the two variables (and a bunch of 100 others) are defined, so "peek definition" and friends don't work as the source file edited does not have it included (only the pre-parsed file contains the copy statement).
I *guess* one would need to hock into the "extract copybook" part and add those copybooknames to the list to be parsed by the cobol extension.

If not: is it possible to include the pre-processing into the extension like in the following scenario:

TEST.COBP is opened in the editor
* on open and on save the custom extension triggers a task that creates the TEST.cob file
* the cobol extension is then "told" to analyze TEST.cob instead of the currently opened not TEST.COBP

**Comment by spgennard** [comment]
I've pondered over the issue in my head for a couple of days and I cannot come up with a solution that does not require you to create a new language for .cobp (or  maybe semantic colouring) , and a custom editor to handle the pre-processor.

In other words... not easy.. and I am not 100% sure it is possible.

I have not seen another editor in vscode do this sort of thing.

This sort of thing is where the big brother of vscode, Visual Studio kicks as it provides a better custom editor model, allowing vendors such as Micro Focus, the ability to create a slicker COBOL editor that integrates with pre-processors for background parsing.

**Comment by GitMensch** [comment]
Thank you for your thoughts and the useful answer.
Actually I totally wanted to create a new language and hoped I could "injectTo": ["source.cobol"]` as done in this repository - Do you say this isn't easy possible with such constructs or would it "just" not be possible to "internally" include the copy statement?

**Comment by spgennard** [comment]
The syntax defined in your pre-processor is unknown to the COBOL scanner, so it will be ignored and I hope it will not cause it to go wrong.

The visualization can be handled in your own language, which is okay but it will be completely unknown to the scanner.

If the custom pre-processor is your own, I might be able to come up with something that allowed you too supplement the parsing of the file, proving the custom pre-processor can spit out these extra files.

For example, alongside TEST.COBP, you had another file, say an ".ini" file eg:

FILE: .vscode_cobol_pp

[TEST.COBP]
Extra.DD.FILE=myFileFD.CPY

This would tell the scanner, to include an extra file when "data division" starts when parsing TEST.COBP.

**Comment by GitMensch** [comment]
That sounds marvelous, to stay "in line" I suggest to use json,

Something like coboleditor.parserhints pointing to a directory and in there one optional json file per source file (the preprocessor can easily create a new file, adjusting one gets messy really fast) with 

```json
{
   "sourceStart": [],
   "WorkingStorage": [],
   "LocalStorage": [],
   "ScreenSection": []
}
```

and contained in these entries a list of copybook names as strings (absolute or "plain").

**Comment by spgennard** [comment]
Issues resolved through changes in the "core" extension not in the custom extension kit
